samples: config/samples.tsv
# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2)
# Units are technical replicates (e.g. lanes, or resequencing of the same biological
# sample).
units: config/units.tsv

# sample_file: /cluster/projects/cesconlab/Projects/CDK4-6iRES_ERposBCa/Exome-seq/Palbo-RExomeseq2020/ExomeSeq/config/samples.tsv
# bed_file: /cluster/projects/cesconlab/Projects/CDK4-6iRES_ERposBCa/Exome-seq/Palbo-RExomeseq2020/ExomeSeq/config/hg38_bed.tsv
# indel_vcf: /cluster/projects/cesconlab/Projects/CDK4-6iRES_ERposBCa/Exome-seq/Palbo-RExomeseq2020/ExomeSeq/config/indels.tsv
# snv_vcf: /cluster/projects/cesconlab/Projects/CDK4-6iRES_ERposBCa/Exome-seq/Palbo-RExomeseq2020/ExomeSeq/config/snvs.tsv

ref:
  # Ensembl species name
  species: homo_sapiens
  # Ensembl release (make sure to take one where snpeff data is available, check 'snpEff databases' output)
  release: 100
  # Genome build
  build: GRCh38

ref_index:
  bwa-index: "/cluster/projects/mcgahalab/ref/genomes/human/GRCh38/BWAIndex"
  genome: "/cluster/projects/mcgahalab/ref/genomes/human/GRCh38/genome.fasta"
  # This reference file is made from rsem-prepare-reference, it will generate the reference.seq is not found
  rsem: "/cluster/projects/mcgahalab/ref/genomes/human/GRCh38/rsemIndex/reference"
  chm13genome: "/cluster/projects/mcgahalab/ref/genomes/human/CHM13/GCF_009914755.1/GCF_009914755.1_T2T-CHM13v2.0_genomic"

intersects:
    snv:
        0001: +1
        0002: +2
        0003: +3
    indel:
        0001: +1
        0002: +2

db:
  kraken: "/cluster/projects/mcgahalab/ref/kraken"

env:
  conda_shell: "~/miniconda3/etc/profile.d/conda.sh"
  r41: "/cluster/projects/mcgahalab/envs/r41"
  picard: "/cluster/home/quever/miniconda3/envs/picard"
  seqtkdir: "/cluster/projects/mcgahalab/bin/seqtk"
  krakencontainer: "/cluster/projects/mcgahalab/envs/containers/krakenuniq"
  
# sample_file: /cluster/home/selghamr/workflows/intialize/ExomeSeq/config/samples.tsv
# bed_file: /cluster/home/selghamr/workflows/intialize/ExomeSeq/config/hg38_bed.tsv
# indel_vcf: /cluster/home/selghamr/workflows/intialize/ExomeSeq/config/indels.tsv
# snv_vcf: /cluster/home/selghamr/workflows/intialize/ExomeSeq/config/snvs.tsv
